### ISSUE TITLE
Add aditional field to `/status` JSON called `bytesProxiedPretty`

### ISSUE THREAD

**Issue by blakev** [syncthing/relaysrv#22]
Add a field that will convert the bytes proxied value into another unit of measurement, which could potentially be set by a command line argument...or, just offer a few different ones.

I'm running relay nodes for the network and need to keep an eye on the traffic, it would be much easier if I could see the `bytesProxied` in gigabytes or terabytes.

**Comment by AudriusButkevicius** [comment]
Sorry, but its an informational endpoint to be consumed by software, not by people, so I don't think we need to do this. 

You can probably write a 2 line python script which does this for you.

**Comment by AudriusButkevicius** [comment]
You can use http://andyleap.net:20000/ in the meanwhile, if its a public relay.
