### ISSUE TITLE
accept4: too many open files

### ISSUE THREAD

**Issue by canton7** [syncthing/relaysrv#23]
```
Nov 15 19:34:54 creek syncthing-relaysrv[24012]: 2015/11/15 19:34:54 server.go:1934: http: Accept error: accept tcp [::]:22070: accept4: too many open files; retrying in 1s
Nov 15 19:34:53 creek syncthing-relaysrv[24012]: 2015/11/15 19:34:53 server.go:1934: http: Accept error: accept tcp [::]:22070: accept4: too many open files; retrying in 1s
Nov 15 19:34:52 creek syncthing-relaysrv[24012]: 2015/11/15 19:34:52 server.go:1934: http: Accept error: accept tcp [::]:22070: accept4: too many open files; retrying in 640ms
Nov 15 19:34:52 creek syncthing-relaysrv[24012]: 2015/11/15 19:34:52 server.go:1934: http: Accept error: accept tcp [::]:22070: accept4: too many open files; retrying in 320ms
Nov 15 19:34:51 creek syncthing-relaysrv[24012]: 2015/11/15 19:34:51 server.go:1934: http: Accept error: accept tcp [::]:22070: accept4: too many open files; retrying in 160ms
Nov 15 19:34:51 creek syncthing-relaysrv[24012]: 2015/11/15 19:34:51 server.go:1934: http: Accept error: accept tcp [::]:22070: accept4: too many open files; retrying in 80ms
Nov 15 19:34:51 creek syncthing-relaysrv[24012]: 2015/11/15 19:34:51 server.go:1934: http: Accept error: accept tcp [::]:22070: accept4: too many open files; retrying in 40ms
Nov 15 19:34:51 creek syncthing-relaysrv[24012]: 2015/11/15 19:34:51 server.go:1934: http: Accept error: accept tcp [::]:22070: accept4: too many open files; retrying in 20ms
Nov 15 19:34:51 creek syncthing-relaysrv[24012]: 2015/11/15 19:34:51 server.go:1934: http: Accept error: accept tcp [::]:22070: accept4: too many open files; retrying in 10ms
Nov 15 19:34:51 creek syncthing-relaysrv[24012]: 2015/11/15 19:34:51 server.go:1934: http: Accept error: accept tcp [::]:22070: accept4: too many open files; retrying in 5ms
```

Sometime around this, the relay dropped off the pool server.

**Comment by canton7** [comment]
I didn't manage to get an `lsof` before restarting it. If it happens again, I'll do that.

**Comment by AudriusButkevicius** [comment]
Hmm, can you check /proc/<pid>/fd (or somrwhere there) what the descriptors are (ls -lah should show that)? Do you have a high number of clients on the relay?

**Comment by canton7** [comment]
I'm not sure how many clients I had I'm afraid - I restarted it when I should have done more debugging.

I'll watch for it happening again and have a look if it does. It only took a couple of hours between being set up and hitting this error, so it might not take long to hit it again...

**Comment by calmh** [comment]
You probably want to up the allowed number of file descriptors. 

(And we should have a way to set a limit and have the relaysrv say "full, go away")

**Comment by AudriusButkevicius** [comment]
Well it happens automatically, we fail to accept the connection and peers go elsewhere as a result.

**Comment by calmh** [comment]
Not very controlled though. Ideally we'd want to stop accepting new listening clients when we reach max_fd/2 or something, to have it be somewhat likely that a listening client is actually able to get a connection with someone else through the relay.

**Comment by canton7** [comment]
Right, it happened again.

 - Not sure how many clients I had. It's not responding to `/status`.
 - `sudo ls /proc/28941/fd | wc -l` also gives `1024`
 - `ulimit -Sn` is set to 1024 (`ulimit -Hn` gives 4096)

It's interesting that it's been dead for over 12 hours ("dead" in the sense that it's dropped off the pool server), yet it's still maxed out its file descriptors. That must be a bunch of devices trying to connect in order to establish relay-based connections, but being unable? If so, it's hardly a case of ""we fail to accept the connection and peers go elsewhere as a result": instead there are 1024ish devices which cannot be connected to?

I'll bump the ulimit, see how long that helps for. We should probably either do a bit cleaner (a la @calmh's suggestion), or document that the ulimit has to be at least a certain value?

**Comment by calmh** [comment]
Yeah. I think we should have the relaysrv deny new listeners at a much earlier stage, to ensure there are some free fd:s for connections. The actual ratio won't be 100% certain automatically (a single client could have 100 relay connections), but at least then we could `ulimit -n 10240` and `relaysrv -max-clients 1024` and pretty sure it'll work most of the time.

**Comment by canton7** [comment]
As another data point, by other relay (which currently has 610 connections, 37 active sessions) has 853 fd's open, so it's not far off crapping out. It's not unusual to have that many connections, looking at the relay list, either. 

I wonder whether that's related to why relays keep dropping off the list...

**Comment by calmh** [comment]
Possibly. We could add code to the startup to increase the limit to at least the hard limit (so you'd get 4096 in your setup by default). And maybe auto dimension the above config value from the number of available fd:s if nothing was set manually.

**Comment by calmh** [comment]
I.e. https://github.com/syncthing/syncthing/blob/master/lib/osutil/rlimit_unix.go

**Comment by canton7** [comment]
Yeah, sounds sensible: we know we're fd-hungry, so we might as well use everything we can.

The systemd scripts can also specify `LimitNOFILE`, to change the hard limit for just that process (for the people that use systemd).

**Comment by AudriusButkevicius** [comment]
So if you ls in the proc directory, as far as I recall it should show what the fds are pointing to. What I want to make sure is that we are not leaking fds.

**Comment by calmh** [comment]
That's a good point. I could expect 610 + 2*37 + some, but that "some" is 169 which is a little bit too much

**Comment by canton7** [comment]
`ls` doesn't show me, but `lsof -u <user>` says that most of them are in the form (all `ESTABLISHED` and `IPv6`)

`877u     IPv6            1629246      0t0     TCP 45.33.63.43:22067->73.212.226.92:57773 (ESTABLISHED)`

We've got a few of these (both TCP and TCPv6):

`854u     sock                0,7      0t0 1528631 protocol: TCP`

And these to start:

```
COMMAND     PID               USER   FD      TYPE             DEVICE SIZE/OFF    NODE NAME
syncthing 22636 syncthing-relaysrv  cwd       DIR                8,0     4096  238576 /var/lib/syncthing-relaysrv
syncthing 22636 syncthing-relaysrv  rtd       DIR                8,0     4096       2 /
syncthing 22636 syncthing-relaysrv  txt       REG                8,0  5917952   36930 /usr/bin/syncthing-relaysrv
syncthing 22636 syncthing-relaysrv  mem       REG                8,0  1991416   26719 /usr/lib/libc-2.22.so
syncthing 22636 syncthing-relaysrv  mem       REG                8,0   146608   26696 /usr/lib/libpthread-2.22.so
syncthing 22636 syncthing-relaysrv  mem       REG                8,0   165592   26718 /usr/lib/ld-2.22.so
syncthing 22636 syncthing-relaysrv    0r      CHR                1,3      0t0    6420 /dev/null
syncthing 22636 syncthing-relaysrv    1u     unix 0xffff88003a103500      0t0  708726 type=STREAM
syncthing 22636 syncthing-relaysrv    2u     unix 0xffff88003a103500      0t0  708726 type=STREAM
syncthing 22636 syncthing-relaysrv    3u     IPv6             708746      0t0     TCP *:22067 (LISTEN)
syncthing 22636 syncthing-relaysrv    4u     IPv6             708739      0t0     TCP *:22070 (LISTEN)
syncthing 22636 syncthing-relaysrv    5u  a_inode               0,11        0    6417 [eventpoll]
```

... so if we're leaking anything, it's established tcp connections? :stuck_out_tongue:

**Comment by AudriusButkevicius** [comment]
Can you netstat -tp | grep relaysrv or something simillar and check if there is a high number of connections to a specific host.

I wonder if we are somehow leaking http calls to the pool srv for example.

**Comment by canton7** [comment]
`netstat -tpn | grep syncthing | awk '{ print $5 }' | sort | uniq | wc -l` and `netstat -tpn | grep syncthing | wc -l` consistently return the same number of results

**Comment by AudriusButkevicius** [comment]
netstat -tpn | grep syncthing | awk '{ print $5 }' | cut -d: -f1 | sort | uniq -c

Ports are unique hence why it matches for you

**Comment by canton7** [comment]
Argh damnit, thanks.

`netstat -tpn | grep syncthing | awk '{ print $5 }' | cut -d: -f1 | sort | uniq -c | sort` gives a few devices with 8 entries, one with 6, 4 with 4, 8 with 3, about 20 with 2, and the rest (600-odd) with 1.

**Comment by canton7** [comment]
My other relay just fell over with this as well btw.

`netstat -tpn | grep syncthing | awk '{ print $5 }' | cut -d: -f1 | sort | uniq -c | sort` gives 

```
      3 162.200.104.243
      3 173.181.52.192
      3 203.86.207.241
      3 24.121.244.45
      3 45.63.59.231
      3 50.173.244.234
      3 61.239.96.128
      3 69.165.165.53
      3 72.223.94.157
      3 72.230.198.76
      3 85.88.191.134
      3 92.63.81.2
      4 101.227.65.193
      4 162.72.226.50
      4 62.249.155.18
      4 76.27.40.174
      4 81.134.132.34
      4 92.50.81.46
      5 115.70.234.113
      5 142.41.247.10
      7 150.104.60.1
      7 89.105.102.158
```

The process has ~1000 fd's open. Looks like exactly the same issue, just took a bit longer to get there.

**Comment by AudriusButkevicius** [comment]
Ok it seems we are genuinely hitting the roof then.

**Comment by calmh** [comment]
My relay has 1607 fd:s open, 1597 established tcp connections, which seems about right. The connections per host breakdown is as follows:

```
[root@relay1 ~]# ls /proc/77864/fd | wc -l
1607
[root@relay1 ~]# netstat -n | grep -c '.443 '
1597
[root@relay1 ~]# netstat -n | grep '.443 ' | awk '{print $2}' | awk 'BEGIN {FS="."} {print $1 "." $2 "." $3 "." $4 }' | sort | uniq -c | sort -n | awk '{print $1}' | uniq -c
   1066 1
    136 2
     34 3
     20 4
      4 5
      1 6
      2 7
      1 8
      1 11
      1 16
[root@relay1 ~]# 
```

That last table means there are 1066 hosts with one connect, 136 hosts with two connects, 34 hosts with 3 connections and so on. Seems legit enough. But we need to be able to limit the number of connections for sure, both total and per host.

**Comment by canton7** [comment]
Ping @rumpelsepp, mind adding `LimitNOFILE=8192` or some such to the arch relaysrv service files?

**Comment by rumpelsepp** [comment]
@canton7  Does adding this setting fix your problem?

**Comment by canton7** [comment]
It seems to: I'm well over the soft limit for that user now and still going strong.

**Comment by canton7** [comment]
Thanks!

**Comment by canton7** [comment]
I think there may still be a leak somewhere. Both relays now have exceeded 4096 FDs, but only after being up for about a month.

```
antony@creek ~ $ sudo netstat -n | grep -c '.443 '
3
antony@creek ~ $ netstat -n | grep '.22067 ' | awk '{print $2}' | awk 'BEGIN {FS="."} {print $1 "." $2 "." $3 "." $4 }' | sort | uniq -c | sort -n | awk '{print $1}' | uniq -c

      7 1
      1 2
      1 3650
antony@creek ~ $ netstat -tpn | grep syncthing | awk '{ print $5 }' | cut -d: -f1 | sort | uniq -c | sort

... gives a 5 IPs with 7, 5 IPs with 6, 6 with 5, 12 with 4, and a ton of 2's and 1's.
```

The `/status' endpoint gives me:

```
{
    "bytesProxied": 2598327837299,
    "goArch": "amd64",
    "goMaxProcs": 2,
    "goOS": "linux",
    "goVersion": "go1.5.1",
    "kbps10s1m5m15m30m60m": [
        15820,
        15989,
        15996,
        15993,
        15996,
        15994
    ],
    "numActiveSessions": 119,
    "numConnections": 2746,
    "numPendingSessionKeys": 0,
    "numProxies": 229,
    "options": {
        "global-rate": 2500000,
        "message-timeout": 60,
        "network-timeout": 120,
        "per-session-rate": 2000000,
        "ping-interval": 60,
        "pools": [
            "https://relays.syncthing.net/endpoint"
        ],
        "provided-by": "canton7"
    },
    "startTime": "2015-12-01T13:46:49.53363984Z",
    "uptimeSeconds": 1933922
}
```

**Comment by canton7** [comment]
I'll leave it struggling on over night (most things it tries to do are thwarted by the lack of available FDs), then restart it tomorrow if you don't want me to get any more info from it.

**Comment by AudriusButkevicius** [comment]
Maybe its something todo with tcp reuse?

**Comment by AudriusButkevicius** [comment]
What does proc show? Is it listing 4k fds? Are most of them sockets? I guess lsof might show something more useful?

**Comment by canton7** [comment]
Relaysrv died this morning:

```
Dec 24 04:00:08 creek systemd[1]: syncthing-relaysrv.service: Failed with result 'exit-code'.
Dec 24 04:00:08 creek systemd[1]: syncthing-relaysrv.service: Unit entered failed state.
Dec 24 04:00:08 creek systemd[1]: Stopped Syncthing relay server.
Dec 24 04:00:08 creek systemd[1]: syncthing-relaysrv.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 24 04:00:07 creek systemd[1]: Stopping Syncthing relay server...
Dec 24 03:15:22 creek syncthing-relaysrv[13741]: 2015/12/24 03:15:22 pool.go:56: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
```

There's nothing in any other logs which is relevant, so it appears it exited on its own (as opposed to being killed by something).

I did have a look in proc last night, and all I could see were open sockets. I didn't count them though, and didn't run `lsof`.

**Comment by calmh** [comment]
```
code=exited, status=2/INVALIDARGUMENT
```

That's probably exit code 2, so a panic or similar?

**Comment by canton7** [comment]
Maybe - it didn't output anything further to stdout. It's located in `/usr/bin`, so can't have written a panic log there. Nothing in its working dir as well.

**Comment by rumpelsepp** [comment]
Maybe the process somehow received a SIGTERM? On Syncthing we already had that case, that a SIGTERM caused the process to exit with exit code 2 (rather than 127 + signal_number); https://github.com/syncthing/syncthing/pull/2581

**Comment by canton7** [comment]
Maybe. Given that it was really struggling for fds, my money's on some Go internals failing in some odd way, so i'm not worried about it.
