### ISSUE TITLE
Update release builds using Go compiler 1.5.1

### ISSUE THREAD

**Issue by blakev** [syncthing/relaysrv#24]
Currently the release is built using 1.4.3, consider using the latest version 1.5.1 for current and future releases of `relaysrv`

**Comment by calmh** [comment]
Currently we're building with 1.4.3 because 1.5.1 doesn't work for Syncthing. Once 1.5.2 is out we'll probably switch everything over to that.

**Comment by AudriusButkevicius** [comment]
So I think we can build relaysrv with go 0.1 alpha, as it does very little, and the version of the compiler should not matter.

**Comment by calmh** [comment]
There may security updates though, especially to the TLS layer. I think staying current is a good default here. But we'll do so when it's reasonable. :)

**Comment by blakev** [comment]
I was hoping garbage collector improvements could benefit a large number of connected clients on slower hardware.

**Comment by AudriusButkevicius** [comment]
It allocates a 1k buffer per connection, there is no garbage otherwise.
