### ISSUE TITLE
Volume quota as an alternative to bandwidth limit

### ISSUE THREAD

**Issue by cyrozap** [syncthing/relaysrv#28]
Instead of charging per-gigabyte, some VPS providers will provide a limited amount of data transfer and will disable the server if it goes over that limit. Currently, to avoid this situation with relaysrv, global and session rate-limiting can be used. Unfortunately, if the most conservative approach is used (`global_rate = num_bytes_transfer/seconds_in_a_month`), the full bandwidth will underutilized since the traffic is rather burst-y. If instead there was an option to limit the total number of bytes transferred, the global rate can be set higher than the conservative limit without the possibility of exceeding the data cap.

I haven't really thought through all the details yet, so feedback would be greatly appreciated.

**Comment by calmh** [comment]
Is a reasonable request, but requires more work than the current setup. (Someone is going to want monthly, someone else daily or weekly, reset ever 30 days from now or on the first day of the month, except tuesdays, etc. ;)

**Comment by canton7** [comment]
Vendan on IRC has an implementation of this which he's been running locally.

**Comment by AudriusButkevicius** [comment]
It's not exactly obvious to me how you'd do this. I'd rather provide 100kb/s slowly but surely across the whole month rather than 100mb/s for a few minutes and loose the relay for the rest of the month.

**Comment by canton7** [comment]
I don't know how Vendan did it, but one approach would be to guarantee a baseline of 100kb/s across the month, but if the actual usage is below this on day 1, the speed is allowed to increase slightly on day 2 to use up the transfer that day 1 didn't consume.

**Comment by andyleap** [comment]
(Vendan on IRC here)  What I did was add another token bucket, that took an entire day to fill.  That token bucket filled at a rate to match your bandwidth allowance (i.e. 100kb/s), and then set the 4 or so second bucket to fill at a rate of double the bandwidth allowance.  This meant that you could burst to double the bandwidth allowance, but only for as long as there was "spare bandwidth" from the past.  This means that the "allowed bandwidth" could never fall below the bandwidth allowance you had set, so we don't have issues with "loosing" relays cause they ate up their bandwidth in the first day.

**Comment by AudriusButkevicius** [comment]
Given you've gone through this, and probably have the code that does this, would it not be wise to make a PR?

**Comment by andyleap** [comment]
I'll have to pull the latest code and clean up some.  My current code is hacky and has several things broken cause I don't use them. (i.e. per session limits and etc.)
