### ISSUE TITLE
basic minimal instructions?

### ISSUE THREAD

**Issue by nogece** [syncthing/relaysrv#3]
Hi,

a relay server makes syncthing a really powerful thing. I am not able to use it without it. If I can sync my work laptop with my workdesktop only when I am in the office (corporate fw...), then where is the point.

I just installed the relay on a machine in the public internet but am stuck. I tried guessing how it could work, but probably some assumptions are wrong. Could you please provide a very basic description on how to use it? Or otherwise, note in the readme that it is not yet usable. Here my guesswork:
 
I can not start the relay without a a certificate (Failed to load X509 key pair: open cert.pem: no such file or directory). I guessed that I have to create one. I did that with 

```
generate_cert/generate_cert --cert=cert.pem --key=key.pem --host=syncthing --org=syncthing
```
Then it starts.
```
go/bin/relaysrv -debug=true -keys="."
```
 I then add a device in syncthing. I can see from the debug log that it does connect. Yet, I get the following error:

```
2015/07/23 15:55:48 Protocol listener accepted connection from 195.66.111.34:54306
2015/07/23 15:55:48 Protocol negotiation error
2015/07/23 15:55:48 Closing connection TEQ6GQS-PTP65JO-IHSEYWP-VRG2DHN-WN4ZW44-PBNM7GM-TV5YQJ3-ZG5QCQ7: xdr read: EOF
```
And in syncthing:
```
2015-07-23 16:00:12: Bad certificate from relay (my.server.ip.addr:22067): x509: certificate is valid for , not syncth
```

What am I doing wrong. I also tried
```
generate_cert/generate_cert --cert=cert.pem --key=key.pem --host=my.server.ipaddr
```
with the same result.

**Comment by calmh** [comment]
There'll be some docs. At the moment this is not yet ready, the code to use it isn't in Syncthing yet.

https://github.com/syncthing/syncthing/pull/1995

**Comment by AudriusButkevicius** [comment]
Readme.md now contains basic instructions.
