### ISSUE TITLE
Too slow session start

### ISSUE THREAD

**Issue by alex73** [syncthing/relaysrv#30]
Hi. My two boxes with syncthing 0.12.15 start connection via relaysrv with huge delay(about 10 minutes).

Configuration is:

host1 and host2 in the internal network, host3 outside behind NAT, host1 also has public IP

host1/relaysrv has address 192.168.1.1 and external IP with name(myhost.com for example)
host2/syncthing has address 192.168.x.x
host3/syncthing has address 10.x.x.x(other internal network)

host1/relaysrv started with -pools=""
host2 and host3 : adress is dynamic, global discovery enabled, relay enabled
relay server host host2 defined as "relay://192.168.1.1:port"
relay server host host3 defined as "relay://myhost.com:port"

Just after starting, syncthing on host2 and host3 finds relay immediately, but display "Disconnected" as device status. Debug of relaysrv displays only "pong" packets.

Probably it will be important: When session started after huge dalay, relaysrv displays source and target very strange. It doesn't display 192.168.x.x as source address(host2), but displays NAT box's external IP of my 192.168. network. Target address(host3) displayed as external IP of 10.x.x.x network(that's good).

**Comment by AudriusButkevicius** [comment]
So your explanation is very unclear and I cannot understand it, but I think this is expected, as it's a by-product of how often we announce address, how often we check for new addresses and the fact that you start all of them at the same time, potentially causing lookups for addresses happen before announcements for addresses.

You can adjust RelayReconnectIntervalM in syncthing on all sides, and see if that helps.

Regardless, this is the wrong repo for this issue, hence closing.
