### ISSUE TITLE
Add documentation for Rest API

### ISSUE THREAD

**Issue by Nutomic** [syncthing/relaysrv#33]
You can get some status information by using `curl localhost:22070/status` on the relay. However, this isn't documented anywhere (that I could find).

**Comment by AudriusButkevicius** [comment]
Nor it's set in stone what it will be.

**Comment by Nutomic** [comment]
Specifically, it isn't even mentioned that this API exists. Maybe you can just mention it in the readme?

**Comment by AudriusButkevicius** [comment]
It mentions it in -help

**Comment by Nutomic** [comment]
Right, but that's rather hidden imo. And it doesn't mention the /status endpoint.
