### ISSUE TITLE
[-listen] and [-status-srv] parameter issues

### ISSUE THREAD

**Issue by martin-rueegg** [syncthing/relaysrv#35]
running v0.12.18

### expected behaviour

- ~~when no `-listen` parameter is given or only contains the port-part (e.g. `-listen ":12345"`), then relaysrv should listen on all addresses, both on **IPv4** _and_ **IPv6**~~
- when `-listen "0.0.0.0:22067"` is given, relaysrv should listen on all  **IPv4** addresses, but not on **IPv6**
- when `-listen ":::22067"`, relaysrv should listen on all  **IPv6** addresses, but not on **IPv4**
- the `-listen` parameter is supplied more than once, every instance of it should be respected

### actual behaviour
- when `-listen "0.0.0.0:22067"` is given, relaysrv listens on IPv6 as well
- when `-listen ":::22067"` is given, relaysrv presumably listens on IPv4 as well
- when the `-listen` parameter is supplied more than once, only the last instance is respected

### status port
the same applies to `-status-srv`

**Comment by AudriusButkevicius** [comment]
How do you know?

**Comment by martin-rueegg** [comment]
@AudriusButkevicius, i checked it with netstat after i could not connect.

(btw: i've updated my initial comment, as i accidentally already posted the issue. sorry for that)

**Comment by AudriusButkevicius** [comment]
Netstat shows :: for both v4 and v6, so thats not a good metric. I am skeptical that this is the case (because we don't explicitly specify a protocol which means dual stack), but I will test it once at home.

**Comment by martin-rueegg** [comment]
you're right, my interpretation of netstat was incorrect. and probably the issue was something else.

however, IPv4-only or IPv6-only and multiple addresses should maybe still be respected. but that would be rather an enhancement, than a bug. same applies to [`discosrv`](https://github.com/syncthing/discosrv/).

**Comment by AudriusButkevicius** [comment]
It seems to be a golang quirk, rather than our quirk.

I've asked the question why:
https://groups.google.com/forum/#!topic/golang-dev/MvAlef3CTqk

I welcome any pull requests fixing this.

**Comment by martin-rueegg** [comment]
cool.

regarding your question
> Yet why is net.Listen("tcp", "192.168.1.2:1234") only listening on v4, even if the same interface has a v6 address?
i would say, that's what to be expected. i can have more than one address on one interface and don't want to listen to them all. if i want to listen on selective addresses, i'd need to specify `-listen` mulitple times and that should call net.Listen multiple times. if it is too difficult to evaluate the same parameter multiple times, a comma-separated list of addresses would be a work-around, like
`-listen "192.168.1.2:1234,192.168.2.2:1234"`
and then something along the lines
`for $ip in split(",", $listen) do net.Listen("tcp", $ip)`

i've never go'ed. so i'll see if i can be of any help.

**Comment by AudriusButkevicius** [comment]
I had people saying on IRC that Go coverts 0.0.0.0 to it's v6 equivalent when listening, which sounds like a pile of bullcrap to me, hence why I gave the analogy.

**Comment by martin-rueegg** [comment]
:-D i see. well, with bullcrap you could at least lit a fire ...

**Comment by calmh** [comment]
No bullshit: http://play.golang.org/p/aNbi6dVg00

That first 0.0.0.0 is 0:0:0:0:0:FFFF:0.0.0.0, an IPv4 mapped IPv6 address.

**Comment by AudriusButkevicius** [comment]
Right, but it doesn't do that for other non-v6 addresses.
