### ISSUE TITLE
Can not launch via systemd

### ISSUE THREAD

**Issue by luqasz** [syncthing/relaysrv#38]
Hi

I am using debian jessie and can not launch relay via systemd:
```
[Unit]
Description=Syncthing relay server
After=network.target

[Service]
User=syncthing-relaysrv
Group=nogroup
ExecStart=/usr/bin/relaysrv -keys /etc/syncthing-relaysrv
WorkingDirectory=/var/lib/syncthing-relaysrv
RootDirectory=/var/lib/syncthing-relaysrv

PrivateTmp=true
ProtectSystem=full
ProtectHome=true
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
```
```
ls -l  /etc | grep relay
drwxr-xr-x 2 syncthing-relaysrv nogroup  4096 kwi 28 23:04 syncthing-relaysrv
```
```
ls -l  /var/lib | grep relay
drwxr-xr-x 2 syncthing-relaysrv nogroup  4096 kwi 28 22:30 syncthing-relaysrv
```
After doing `systemctl start syncthing-relaysrv`
```
systemctl status syncthing-relaysrv
● syncthing-relaysrv.service - Syncthing relay server
   Loaded: loaded (/etc/systemd/system/syncthing-relaysrv.service; enabled)
   Active: failed (Result: exit-code) since czw 2016-04-28 23:02:01 CEST; 39min ago
  Process: 4693 ExecStart=/usr/bin/relaysrv -keys /etc/syncthing-relaysrv (code=exited, status=200/CHDIR)
 Main PID: 4693 (code=exited, status=200/CHDIR)
```
I can launch it (If I change users shell to `/bin/bash`) manually from `syncthing-relaysrv` user. Any idea why I can not launch it from systemd ?

**Comment by AudriusButkevicius** [comment]
Did you manage to start it without systemd?

**Comment by luqasz** [comment]
Yes. As I stated before.

**Comment by AudriusButkevicius** [comment]
https://www.freedesktop.org/software/systemd/man/systemd.exec.html
Root directory puts the process in a chroot, and working dir tries to cd into the directory, essentially resulting in trying to run in /var/lib/syncthing-relaysrv/var/lib/syncthing-relaysrv

**Comment by luqasz** [comment]
Ok. Thx.
I've removed `RootDirectory` from systemd service file and it works 👍 
I've copied https://github.com/syncthing/relaysrv/blob/master/etc/linux-systemd/syncthing-relaysrv.service and modified it a bit. Seems that `RootDirectory` causes trouble there.

**Comment by AudriusButkevicius** [comment]
Yeah I'll scrap it.
