### ISSUE TITLE
Ensuring quality of public relay servers

### ISSUE THREAD

**Issue by MikeLund** [syncthing/relaysrv#40]
Hi, is there any system built into the relays system that ensures that hosts are offering a quality relay? Of course we should assume good-faith in hosts, but is there any kind of statistic to see if a relay is frequently offering a low-quality relay or such?

I doubt (at least at this point) that someone would modify a relay server intentionally to disrupt syncing for non-portforwarded users, but basically my question could be, what failsafes are built into Syncthing to prevent this from happening?

Looked around and couldn't find much about this aspect of relay security. Thanks for infos and such (and hopefully this will exist as a feature request if such is needed! :))

**Comment by AudriusButkevicius** [comment]
The pool server checks if connecting via relay works before admitting it to the pool, but that's about it. I guess we could ban the relay from the pool if we see abuse, though I think there always will be ways to trick the pool server if you deliberately want to cause damage.

**Comment by AudriusButkevicius** [comment]
If anything, this should live in the relaypoolsrv repo, hence closing this.
