### ISSUE TITLE
Understanding parameter -global-rate

### ISSUE THREAD

**Issue by dionysius** [syncthing/relaysrv#41]
Context: I have up 10Mbit/s and down 10Mbit/s, I want to configure that it uses 5Mbit/s each.

5Mbit/s = 625000 B/s (afair)

Do 625000 mean 625000 up AND 625000 down, or are they halfed each so total (both together) is 625000?

global != total (?)

for me the "global" word needs some little more context - it's not clear to me.

**Comment by AudriusButkevicius** [comment]
All traffic is symetrical regardless of up/down, as we are relaying traffic, so everything applies to the session as a whole, both ways.

**Comment by AudriusButkevicius** [comment]
And global is the limit across all sessions, all connections all ways.
