### ISSUE TITLE
How to add Relay Server URI in client?

### ISSUE THREAD

**Issue by Ranler** [syncthing/relaysrv#42]
> This URI can then be used in syncthing as one of the relay servers.

I have deploy a relay server, and have a `relay://IP:PORT` URI.
but how to use this URI in client?

I have try to add `<relayServer>relay://IP:PORT</relayServer>` in `config.xml`, but it seems not work.

**Comment by AudriusButkevicius** [comment]
In the docs it says that it's one of the listen addresses now

**Comment by Ranler** [comment]
Thanks. It works to put URI in `<listenAddress>` of `config.xml`.
