### ISSUE TITLE
downloadlink down/changed

### ISSUE THREAD

**Issue by SkyBlock4000** [syncthing/relaysrv#43]
Downloadlink changed from http://build.syncthing.net/job/relaysrv/lastSuccessfulBuild/artifact/ to https://build.syncthing.net/job/strelaysrv/lastSuccessfulBuild/artifact/

**Comment by AudriusButkevicius** [comment]
You can modify the readme via github text editor ui and make a pull request

**Comment by SkyBlock4000** [comment]
created a pull request.
thanks for the info.
